import { rmSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { defineConfig } from 'astro/config'
import sitemap from '@astrojs/sitemap'
import tailwindcss from '@tailwindcss/vite'
import expressiveCode from 'astro-expressive-code'
import { verifyArtifacts } from './scripts/artifacts.mjs'

const root = fileURLToPath(new URL('.', import.meta.url))

// typeshade.dev: a static site built from the compiler vendored at vendor/shader-dsl. Every
// code sample and number on the page is computed from that checkout at build time.
export default defineConfig({
  site: 'https://typeshade.dev',
  output: 'static',
  trailingSlash: 'ignore',
  // English at /, every other locale under its own prefix. The copy lives in src/i18n.
  i18n: { defaultLocale: 'en', locales: ['en', 'ko'], routing: { prefixDefaultLocale: false } },
  integrations: [
    // og.png, the icons and the canvas stills are generated by scripts and committed with a
    // .sha256 each. The build checks the hashes instead of running a browser.
    { name: 'typeshade:artifact-hashes', hooks: { 'astro:build:start': () => verifyArtifacts(root) } },
    // /og/ exists only so capture-og.ts can photograph it.
    {
      name: 'typeshade:og-route',
      hooks: {
        'astro:build:done': ({ dir }) => {
          if (process.env.OG_REBASELINE === '1') return
          rmSync(fileURLToPath(new URL('og/', dir)), { recursive: true, force: true })
        },
      },
    },
    expressiveCode(),
    sitemap({
      filter: (page) => new URL(page).pathname.replace(/\/$/, '') !== '/og',
      i18n: { defaultLocale: 'en', locales: { en: 'en', ko: 'ko' } },
    }),
  ],
  vite: { plugins: [tailwindcss()] },
})
