import { copyFileSync, rmSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';
import tailwindcss from '@tailwindcss/vite';
import expressiveCode from 'astro-expressive-code';
import remarkApiLinks from './src/lib/remark-api-links.mjs';
import remarkDocTables from './src/lib/remark-doc-tables.mjs';
import remarkErrorLinks from './src/lib/remark-error-links.mjs';
import remarkPackageName from './src/lib/remark-package-name.mjs';
import remarkPromoteBoldLeads from './src/lib/remark-promote-bold-leads.mjs';
import remarkRuleLinks from './src/lib/remark-rule-links.mjs';
import { verifyArtifacts } from './scripts/artifacts.mjs';
import { verifyKoreanFonts } from './scripts/fonts.mjs';

const root = fileURLToPath(new URL('.', import.meta.url));

// typeshade.dev: a static site built from the compiler vendored at vendor/shader-dsl. Every
// code sample and number on the page is computed from that checkout at build time.
export default defineConfig({
  site: 'https://typeshade.dev',
  output: 'static',
  trailingSlash: 'always',
  // The docs moved under /guide/ on the day the site launched; the first routes redirect.
  redirects: Object.fromEntries(
    Object.entries({
      '/motivation/': '/guide/introduction/',
      '/checks/': '/guide/checks/',
      '/examples/': '/guide/examples/',
      '/guide/': '/guide/introduction/',
    }).flatMap(([from, to]) => [
      [from, to],
      [`/ko${from}`, `/ko${to}`],
    ]),
  ),
  // English at /, every other locale under its own prefix. The copy lives in src/i18n.
  i18n: { defaultLocale: 'en', locales: ['en', 'ko'], routing: { prefixDefaultLocale: false } },
  integrations: [
    // og.png, the icons and the canvas stills are generated by scripts and committed with a
    // .sha256 each. The build checks the hashes instead of running a browser.
    {
      name: 'typeshade:artifact-hashes',
      hooks: {
        'astro:build:start': () => {
          verifyArtifacts(root);
          verifyKoreanFonts(root);
        },
      },
    },
    // /og/ exists only so capture-og.ts can photograph it, and /capture-stills/ only so
    // capture-stills.ts can; neither is served.
    {
      name: 'typeshade:capture-routes',
      hooks: {
        'astro:build:done': ({ dir }) => {
          if (process.env.OG_REBASELINE !== '1')
            rmSync(fileURLToPath(new URL('og/', dir)), { recursive: true, force: true });
          if (process.env.STILLS_REBASELINE !== '1')
            rmSync(fileURLToPath(new URL('capture-stills/', dir)), {
              recursive: true,
              force: true,
            });
        },
      },
    },
    expressiveCode(), // options in ec.config.mjs
    sitemap({
      filter: (page) =>
        ![
          '/og',
          '/capture-stills',
          '/motivation',
          '/checks',
          '/examples',
          '/guide',
          '/ko/motivation',
          '/ko/checks',
          '/ko/examples',
          '/ko/guide',
          '/ko/404',
        ].includes(new URL(page).pathname.replace(/\/$/, '')) &&
        // /guide/authoring/ and its sections only redirect to /guide/internals/.
        !/^\/(ko\/)?guide\/authoring\//.test(new URL(page).pathname),
      // No lastmod: one build date on every URL tells a crawler nothing, and Google stops
      // reading a sitemap's lastmod once it proves inaccurate.
      i18n: { defaultLocale: 'en', locales: { en: 'en', ko: 'ko' } },
    }),
    // Crawlers and people still ask for /sitemap.xml; serve the index there too.
    {
      name: 'typeshade:sitemap-alias',
      hooks: {
        'astro:build:done': ({ dir }) => {
          copyFileSync(
            fileURLToPath(new URL('sitemap-index.xml', dir)),
            fileURLToPath(new URL('sitemap.xml', dir)),
          );
        },
      },
    },
  ],
  // The package name first, then the guide's first mention of each export as a link to its
  // reference page, and the first mention of each error code and each design rule as a link to
  // its page.
  markdown: {
    remarkPlugins: [
      remarkPackageName,
      remarkPromoteBoldLeads,
      remarkDocTables,
      remarkApiLinks,
      remarkErrorLinks,
      remarkRuleLinks,
    ],
  },
  vite: { plugins: [tailwindcss()] },
});
